### ISSUE TITLE
Moratoriums

### ISSUE THREAD

**Issue by anastasia** [Unnamed-Lab-DUSP/utility_datasets#2]
Expanded into neighborhoods, from https://github.com/Unnamed-Lab-DUSP/evicting_lawyers/issues/7

https://docs.google.com/spreadsheets/d/1X5wGyg9efzT-uqC4EaTZiIHGREBiYRtbgZ2qxqAfFJU/edit#gid=1784461388

**Comment by ericrobskyhuntley** [comment]
This seems like a derived table that should probably just get constructed in the context of a given workflow! (I.e., all neighborhoods in Boston share a start/end date with Boston.) I currently handle this in `flag_local_mora()` in `loader.R` like this...

https://github.com/Unnamed-Lab-DUSP/evicting_lawyers/blob/96bdce97d84d3bd345873b121a92669ea832bacd/scripts/loader.R#L157-L182
